# Generated by Django 3.1.7 on 2021-03-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companyinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='companyId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crudapi.companyinfo'),
            preserve_default=False,
        ),
    ]
