# Generated by Django 3.1.7 on 2021-03-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0004_remove_employee_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companyinfo',
        ),
    ]
