# Generated by Django 3.1.7 on 2021-03-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0006_auto_20210308_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
    ]
